Added 'value' field to the getLastInterruptPin function
adafruit/Adafruit-MCP23017-Arduino-Library pull request #84
Opened 2022-01-30 08:49 UTC by surfermarty

In the getLastInterruptPin function, the INTCAP value is read to clear the interrupt, but without an argument, so the actual value of INTCAP is lost. As this contains the value that caused the interrupt, it is worth keeping - the current value of the pin may have changed since, so a digitalRead isn't ideal - especially if the MCP23008 stores the value that caused the interrupt in the first place.

Patch to add a pointer to an optional 'value' argument that will return the INTCAP value. As it's an optional argument, it doesn't change existing calls to the function that didn't care about the INTCAP value and didn't supply somewhere to store it.

2022-01-31 18:17 UTC, ladyada requested changes

2022-01-31 18:17 UTC, ladyada commented on src/Adafruit_MCP23XXX.cpp
> +    INTCAP.read(value);
what happens if value is NULL, does this crash?

2022-01-31 18:17 UTC, ladyada commented
hiya! thanks so much for submitting a PR! we can review & merge PRs once they have passed continuous integration (CI). that means that code compiles cleanly for all tested platforms, is clang formatted so we maintain the same text formatting for all new code, and is doxygen documented.
if your code isnt passing, check the CI output (click on the red X next to the PR to scroll through the log and find where the error is

here is a tutorial on doxygen: https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

and clang-format: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

and overall how to contribute PRs to libraries: https://learn.adafruit.com/contribute-to-arduino-with-git-and-github

once you get that green checkmark that indicates CI has passed, please comment reply to this post so we know its time for another review (we may not get notified on CI pass and miss that its time to look!)

2022-03-25 16:40 UTC, caternuson commented
Prior to the 2.0.0 release, there was a `getLastInterruptPinValue()` method:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/blob/65438e94ef5cdeb73d7a79d37b8ca46ee9331cd2/Adafruit_MCP23017.cpp#L338-L348
At this point, not sure why that went away. Probably related to the major refactor. Could bring it back maybe?

2022-03-25 21:16 UTC, caternuson commented
Looks like maybe the two methods `getLastInterruptPin()` and  `getLastInterruptPinValue()` were combined as part of the refactor, with this essentially being the code for the later, which is now in the former:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/blob/0e82c8d873037ff2522b9167ac20433ac23ef0d4/src/Adafruit_MCP23XXX.cpp#L242-L248
but without saving or returning the value from `INTCAP`.

Not sure my reasoning for that. Maybe, at the time, did not understand the need for the two separate functions, so combined them.

Some info from datasheet to help clarify behavior of `INTF` vs `INTCAP`:
![image](https://user-images.githubusercontent.com/8755041/160200343-15fd32cc-431d-43c8-a628-37ba981de20d.png)

So `INTF` changes and is like the current state of interrupts, where as `INTCAP` latches the first interrupt state after a previous clear. Reading `INTF` does nothing in terms of clearing interrupts. Reading `INTCAP` does clear interrupt.

Probably best to undo the refactor and put the `INTCAP` read/clear code back into `getLastInterruptPinValue()`. The functions names could probably be better also, to help reflect the differences in behavior. But for now, can address that with better documentation.

2022-03-25 22:27 UTC, caternuson commented
@surfermarty Did you use the functions from the previous library version? Prior to the 2.0.0 update. Looking at the previous code for `getLastInterruptPinValue()`, I have questions about what it's doing and wonder if the previous library actually worked as expected.

2022-03-25 23:02 UTC, surfermarty commented
I didn't look at older versions of the code.

To me, if an interrupt occurs and the pin causing it is stored in INTCAP, then getting the value corresponding to that interrupt makes sense and follows a logical process.

Values of subsequent interrupts in INTF is a different issue/request/feature IMO.

2022-03-25 23:13 UTC, caternuson commented
Thanks. That's my thinking also. Not sure why the previous code started by reading the current state of `INTF`. Seems like it should just read and return `INTCAP`. No need to even pre-check if there's actually an interrupt. Just read and return - with some minor logic added for turning the register value(s) into a `uint8_t` to indicate the pin number.

2022-03-29 20:41 UTC, caternuson commented
The CircuitPython library is also following that general idea:
https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/blob/main/adafruit_mcp230xx/mcp23017.py
There's no special connection between the INTF and INTCAP registers.

There's no need to repeat what the previous library was doing. I'd suggest removing the code that clears INTCAP:
https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/blob/0e82c8d873037ff2522b9167ac20433ac23ef0d4/src/Adafruit_MCP23XXX.cpp#L242-L248
from `getLastInterruptPin()` and add a new method that just reads and returns INTCAP. Could call it `getCapturedInterruptPin()`?

2022-05-09 07:30 UTC, bespezzano commented
Hi, is this getting pushed? I was trying to use it  as it is now but didn't work as the interrupt is triggered but can't get the value of the pin at the trigger point.

2022-10-29 15:18 UTC, caternuson commented
Closing due to lack of updates. Feature was added with #89.

2022-10-29 15:18 UTC, closed without merging